### ISSUE TITLE
Spinlock is improperly implemented

### ISSUE THREAD

**Issue by linuxuser27** [linuxuser27/disvm#9]
`inefficient_spin_lock_t` constructor should be:

```c++
while (_lf.test_and_set())
    ;
```

Ported from https://bitbucket.org/linuxuser27/disvm/issues/16/spinlock-is-improperly-implemented

**Comment by mingodad** [comment]
This doesn't seem to be working, maybe you've missed any other changes on this commit, see https://github.com/linuxuser27/disvm/issues/18
